### ISSUE TITLE
ModelViewSet broken on Python 2.7

### ISSUE THREAD

**Issue by mblayman** [django-json-api/django-rest-framework-json-api#309]
The `ModelViewSet` uses a Python 3 style `super` call in `get_queryset`.

```pytb
Traceback (most recent call last):
  File "~/sample/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "~/sample/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "~/sample/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "~/sample/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "~/sample/lib/python2.7/site-packages/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "~/sample/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "~/sample/lib/python2.7/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "~/sample/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "~/sample/lib/python2.7/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "~/sample/lib/python2.7/site-packages/rest_framework_json_api/views.py", line 35, in get_queryset
    qs = super().get_queryset(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by approxit** [comment]
Any chances for build-in fix?

**Comment by mblayman** [comment]
This is was fixed in https://github.com/django-json-api/django-rest-framework-json-api/commit/cdb8a52a8358b34802f9851a7329e85e1a52ac97.

**Comment by miguelgr** [comment]
When is this gonna be publish for PyPI ?
