### ISSUE TITLE
Membership in list filter failing

### ISSUE THREAD

**Issue by thogerb** [django-json-api/django-rest-framework-json-api#647]
Hi - amazing project you have going on here! Quite a delight working with and also seeing that it's being developed on.

I ran into an issue yesterday with filtering, which I couldn't solve. It might be a bug, or else I am not understanding the docs on setting it up -- in either case help would be appreciated. 

## Expected behavior:

To be able to filter on a list of values like it says in the docs: "Membership in a list of values: ?filter[name.in]=abc,123,zzz (name in ['abc','123','zzz'])"

* My url query is simply "categories/?filter[id.in]=1,2,3" 
* I have set the DjangoFilterBackend as a default in settings
* I have added filterset_fields on the viewset

## Experienced behavior:

If raises **ValidationError: [ErrorDetail(string='invalid filter[id__in]', code='invalid')]**. 

## Traceback

Traceback (most recent call last):
  File "... lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "... lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File ".../lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File ".../lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File ".../lib/python3.6/site-packages/rest_framework/renderers.py", line 732, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File ".../lib/python3.6/site-packages/rest_framework/renderers.py", line 709, in get_context
    'filter_form': self.get_filter_form(data, view, request),
  File ".../lib/python3.6/site-packages/rest_framework/renderers.py", line 641, in get_filter_form
    html = backend().to_html(request, queryset, view)
  File ".../lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 99, in to_html
    filterset = self.get_filterset(request, queryset, view)
  File ".../lib/python3.6/site-packages/rest_framework_json_api/django_filters/backends.py", line 90, in get_filterset
    self._validate_filter(kwargs.pop('filter_keys'), filterset_class)
  File ".../lib/python3.6/site-packages/rest_framework_json_api/django_filters/backends.py", line 79, in _validate_filter
    raise ValidationError("invalid filter[{}]".format(k))
rest_framework.exceptions.ValidationError: [ErrorDetail(string='invalid filter[id__in]', code='invalid')]

## Hope you can help

Looking forward to hearing from you and hope you can help! (I fixed the filtering problem in a very hacky and temporary way, so no rush).

**Comment by n2ygk** [comment]
Please share (preferably a repo that can reproduce the error):
- requirements.txt (e.g. pip package versions)
- views.py, serializers.py, etc.

This looks like you might be doing an HTML-formatted query rather than 'Application/vnd.api+json' but it's hard to reproduce without a full example.

**Comment by thogerb** [comment]
Sure. I actually just got it working, seeing that is was possible to specify it explicitly on the viewset with:

    filterset_fields = {
       'name': ('exact', 'lt', 'gt', 'gte', 'lte', 'in'),
    }

Didn't realize this was insufficient:

    filterset_fields = ('name',)

Vanilla project where the later is failing https://github.com/thogerb/test_filter. Model, serializer and viewset in this test are all in models.py for simplicity

But issue fixed for me, so we can close. Thanks for getting back to me.

**Comment by n2ygk** [comment]
Glad it worked out.
